#!/bin/bash
set -euo pipefail

# =============================================================================
# setup-firewall.sh — Firewall & Intrusion Prevention Setup
# ITS Connect — https://itsconnect.com.br
#
# Installs and configures UFW (Uncomplicated Firewall) with a default-deny
# policy, then installs Fail2Ban with jails for SSH and Nginx.
#
# Usage: sudo ./setup-firewall.sh
# =============================================================================

# ---- Configuration (edit these before running) ------------------------------

SSH_PORT="${SSH_PORT:-19530}"            # Must match your sshd_config Port
FAIL2BAN_BANTIME="${FAIL2BAN_BANTIME:-3600}"    # Ban duration in seconds (1 hour)
FAIL2BAN_MAXRETRY="${FAIL2BAN_MAXRETRY:-5}"     # Attempts before ban
FAIL2BAN_FINDTIME="${FAIL2BAN_FINDTIME:-600}"   # Window for counting retries (10 min)

# ---- Preflight checks ------------------------------------------------------

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root (use sudo)." >&2
    exit 1
fi

# =============================================================================
# PART 1: UFW (Uncomplicated Firewall)
# =============================================================================

echo "========================================"
echo "  Part 1: UFW Firewall Configuration"
echo "========================================"

# ---- Install UFW if not present ---------------------------------------------

echo "[1/5] Installing UFW..."
if ! command -v ufw &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq ufw
    echo "      UFW installed."
else
    echo "      UFW already installed."
fi

# ---- Set default policies ---------------------------------------------------
# Default deny incoming: blocks all unsolicited inbound traffic. This is the
# most important rule — only explicitly allowed services will be reachable.
# Default allow outgoing: permits the server to make outbound connections
# (package updates, API calls, DNS resolution, etc.).

echo "[2/5] Setting default policies (deny incoming, allow outgoing)..."
ufw default deny incoming
ufw default allow outgoing

# ---- Allow essential services -----------------------------------------------
# Only open the ports that are strictly necessary for the server to function.
# Each allowed port increases the attack surface.

echo "[3/5] Allowing essential services..."

# SSH on custom port — required for remote administration
ufw allow "${SSH_PORT}/tcp" comment "SSH (custom port)"
echo "      Allowed SSH on port ${SSH_PORT}/tcp"

# HTTP — required for web traffic and Let's Encrypt ACME challenges
ufw allow 80/tcp comment "HTTP"
echo "      Allowed HTTP on port 80/tcp"

# HTTPS — required for encrypted web traffic
ufw allow 443/tcp comment "HTTPS"
echo "      Allowed HTTPS on port 443/tcp"

# ---- Enable logging ---------------------------------------------------------
# UFW logging records blocked and allowed connections to syslog, which is
# essential for security auditing and incident investigation.

echo "[4/5] Enabling UFW logging..."
ufw logging on

# ---- Enable UFW -------------------------------------------------------------
# The --force flag prevents the interactive confirmation prompt.
# WARNING: If SSH is on port 22 and you didn't allow it above, you will
# be locked out of the server.

echo "[5/5] Enabling UFW..."
ufw --force enable
echo "      UFW is active and enforcing rules."

echo ""
ufw status verbose
echo ""

# =============================================================================
# PART 2: Fail2Ban
# =============================================================================

echo "========================================"
echo "  Part 2: Fail2Ban Configuration"
echo "========================================"

# ---- Install Fail2Ban -------------------------------------------------------

echo "[1/3] Installing Fail2Ban..."
if ! command -v fail2ban-client &>/dev/null; then
    apt-get update -qq
    apt-get install -y -qq fail2ban
    echo "      Fail2Ban installed."
else
    echo "      Fail2Ban already installed."
fi

# ---- Configure Fail2Ban jails -----------------------------------------------
# We use jail.local to override jail.conf defaults. This file survives
# package upgrades (jail.conf gets overwritten, jail.local does not).

echo "[2/3] Configuring Fail2Ban jails..."

cat > /etc/fail2ban/jail.local <<JAILEOF
# =============================================================================
# Fail2Ban Local Configuration — ITS Connect
# Generated by setup-firewall.sh on $(date +%Y-%m-%d)
# =============================================================================

[DEFAULT]
# Ban duration: how long an offending IP is blocked
bantime  = ${FAIL2BAN_BANTIME}

# Find time: the window in which retries are counted
findtime = ${FAIL2BAN_FINDTIME}

# Max retries before banning
maxretry = ${FAIL2BAN_MAXRETRY}

# Use UFW as the ban action (integrates with our firewall)
banaction = ufw

# ---- SSH Jail ---------------------------------------------------------------
# Monitors authentication failures in the SSH log. This is the single most
# important jail — SSH brute-force is the #1 attack vector on public servers.
[sshd]
enabled  = true
port     = ${SSH_PORT}
logpath  = /var/log/auth.log
maxretry = 3
bantime  = 7200

# ---- Nginx HTTP Auth Jail ---------------------------------------------------
# Monitors failed HTTP Basic Authentication attempts against Nginx.
# Catches brute-force attacks on password-protected admin panels and APIs.
[nginx-http-auth]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/error.log
maxretry = 5

# ---- Nginx Bot Search Jail -------------------------------------------------
# Detects bots scanning for common exploit paths (wp-admin, phpmyadmin,
# .env files, etc.) and bans them. Reduces log noise and server load.
[nginx-botsearch]
enabled  = true
port     = http,https
logpath  = /var/log/nginx/access.log
maxretry = 5
bantime  = 3600
JAILEOF

echo "      Jails configured: sshd, nginx-http-auth, nginx-botsearch"

# ---- Restart Fail2Ban -------------------------------------------------------

echo "[3/3] Restarting Fail2Ban..."
systemctl enable fail2ban
systemctl restart fail2ban
echo "      Fail2Ban is active."

echo ""
fail2ban-client status
echo ""

# ---- Summary ----------------------------------------------------------------

echo "============================================="
echo "  Firewall & Fail2Ban Setup Complete"
echo "============================================="
echo "  UFW:          ACTIVE (default deny incoming)"
echo "  SSH port:     ${SSH_PORT}/tcp ALLOWED"
echo "  HTTP:         80/tcp ALLOWED"
echo "  HTTPS:        443/tcp ALLOWED"
echo "  Fail2Ban:     ACTIVE"
echo "  Jails:        sshd, nginx-http-auth, nginx-botsearch"
echo "  Ban time:     ${FAIL2BAN_BANTIME}s (sshd: 7200s)"
echo "  Max retries:  ${FAIL2BAN_MAXRETRY} (sshd: 3)"
echo "============================================="
